@startuml

abstract transporte{
acelerar()
frenar()
bocinar()
estacionado()
}


interface acciones{
acelerar()
frenar()
}
class automovil implements acciones
class carrojuguete extends automovil
class autocomun extends automovil

@enduml
