@startuml

abstract transporte{
acelerar()
frenar()
bocinar()
estacionado()
}


interface acciones{
acelerar()
frenar()
}
class automovil 
automovil o-- acciones
class frenar implements acciones
class acelerar implements acciones
class carrojuguete extends automovil
class autocomun extends automovil

@enduml
